language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run dev
  - aws s3 cp dist/ s3://nextletterapp.com --recursive
before_deploy:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local-dir: dist
  on:
    branch: main
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
